import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-900 text-white min-h-screen">
        <nav className="p-4 bg-gray-800 shadow-md">
          <h2 className="text-xl font-bold">Crypto Dashboard</h2>
        </nav>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}